# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tagged Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build promdump
      working-directory: ./promdump
      # github.ref_name is the tag or branch name
      run: |
        go get
        go build -ldflags=" -X 'main.AppVersion=${{ github.ref_name }}' -X 'main.CommitHash=$(git rev-parse HEAD)' -X 'main.BuildTime=$(date -Iseconds)'" -v ./...

    - name: Test promdump
      working-directory: ./promdump
      run: go test -v ./...

    - name: Build promremotewrite
      working-directory: ./promremotewrite
      # github.ref_name is the tag or branch name
      run: |
        go get
        go build -ldflags=" -X 'main.AppVersion=${{ github.ref_name }}' -X 'main.CommitHash=$(git rev-parse HEAD)' -X 'main.BuildTime=$(date -Iseconds)'" -v ./...

    - name: Test promremotewrite
      working-directory: ./promremotewrite
      run: go test -v ./...

    - name: Compress artifacts
      run: |
        gzip promdump/promdump
        gzip promremotewrite/promremotewrite

    - name: Upload promdump
      uses: actions/upload-artifact@v3
      with:
        name: promdump
        path: promdump/promdump.gz
        
    - name: Upload promremotewrite
      uses: actions/upload-artifact@v3
      with:
        name: promremotewrite
        path: promremotewrite/promremotewrite.gz
